#!/usr/bin/env bash
# =============================================================================
# check_regression.sh - SQLRustGo 性能回归检测脚本
# =============================================================================
# 用法:
#   ./scripts/gate/check_regression.sh                # 检测（运行测试 + 对比）
#   ./scripts/gate/check_regression.sh --skip-run      # 仅对比（不实际跑）
#   ./scripts/gate/check_regression.sh --save-baseline # 把当前测试结果保存为基线
#
# 退出码:
#   0 = PASS  (Δ ≤ 5%)
#   1 = FAIL  (Δ > 20% 任意一项)
#   2 = WARN  (5% < Δ ≤ 20%)
# =============================================================================

set -e

# -------- 参数解析 --------
SKIP_RUN=0
SAVE_BASELINE=0
for arg in "$@"; do
    case "$arg" in
        --skip-run)      SKIP_RUN=1 ;;
        --save-baseline) SAVE_BASELINE=1 ;;
        -h|--help)
            sed -n '2,12p' "$0"
            exit 0
            ;;
        *) echo "Unknown arg: $arg"; exit 1 ;;
    esac
done

# -------- 路径 --------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BASELINE_FILE="$PROJECT_ROOT/data/qps_baseline.json"
CURRENT_FILE="$PROJECT_ROOT/data/qps_current.json"
REPORT_DIR="$PROJECT_ROOT/docs/releases/regression"
mkdir -p "$REPORT_DIR"

# -------- 阈值 --------
WARN_THRESHOLD=5    # 百分比
FAIL_THRESHOLD=20   # 百分比
REPORT_FILE="$REPORT_DIR/regression-$(date +%Y%m%d-%H%M%S).md"

echo "=== SQLRustGo Regression Check ==="
echo "Date:        $(date)"
echo "Branch:      $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
echo "Commit:      $(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
echo "Baseline:    $BASELINE_FILE"
echo "Current:     $CURRENT_FILE"
echo "Skip run:    $SKIP_RUN"
echo ""

# -------- 保存基线 --------
if [ "$SAVE_BASELINE" = "1" ]; then
    if [ ! -f qps_results.log ]; then
        echo "❌ qps_results.log not found. Run benchmarks first."
        exit 1
    fi
    # 取日志最后一次的 4 项结果
    echo "{" > "$BASELINE_FILE"
    echo "  \"saved_at\": \"$(date -Iseconds)\"," >> "$BASELINE_FILE"
    echo "  \"commit\": \"$(git rev-parse --short HEAD 2>/dev/null)\"," >> "$BASELINE_FILE"
    for op in DELETE INSERT SELECT UPDATE; do
        LAST=$(grep "$op QPS:" qps_results.log | tail -1 | grep -oP '\(\K[0-9.]+')
        if [ -n "$LAST" ]; then
            echo "  \"$op\": $LAST," >> "$BASELINE_FILE"
        fi
    done
    echo "  \"_note\": \"Generated by check_regression.sh --save-baseline\"" >> "$BASELINE_FILE"
    echo "}" >> "$BASELINE_FILE"
    echo "✅ Baseline saved to $BASELINE_FILE"
    cat "$BASELINE_FILE"
    exit 0
fi

# -------- 跑测试（可选）--------
if [ "$SKIP_RUN" = "0" ]; then
    echo ">>> Running QPS benchmark (this may take ~1 min) ..."
    cargo test --test qps_benchmark_test -- --ignored --nocapture --test-threads=1 2>&1 | tail -20
fi

# -------- 检查文件存在 --------
if [ ! -f "$BASELINE_FILE" ]; then
    echo "❌ Baseline not found: $BASELINE_FILE"
    echo "   Run with --save-baseline first."
    exit 1
fi

if [ ! -f qps_results.log ]; then
    echo "❌ qps_results.log not found"
    exit 1
fi

# -------- 解析当前数据 --------
echo ">>> Parsing current results ..."
declare -A CURRENT
for op in DELETE INSERT SELECT UPDATE; do
    LAST=$(grep "$op QPS:" qps_results.log | tail -1 | grep -oP '\(\K[0-9.]+')
    if [ -n "$LAST" ]; then
        CURRENT[$op]=$LAST
        echo "  $op current: $LAST"
    fi
done

# -------- 解析基线数据 --------
echo ">>> Parsing baseline ..."
declare -A BASELINE
for op in DELETE INSERT SELECT UPDATE; do
    VAL=$(grep "\"$op\"" "$BASELINE_FILE" | grep -oP ':\s*\K[0-9.]+' | head -1)
    if [ -n "$VAL" ]; then
        BASELINE[$op]=$VAL
        echo "  $op baseline: $VAL"
    fi
done

# -------- 计算 Δ% --------
echo ""
echo ">>> Comparing ..."
echo ""
printf "%-10s %-12s %-12s %-10s %-10s %-8s\n" "OP" "Baseline" "Current" "Δ%" "Direction" "Status"
echo "---------------------------------------------------------------"

WORST_STATUS="PASS"
WORST_OP=""
WORST_DELTA=0

{
    echo "# 回归检测报告"
    echo ""
    echo "**时间**: $(date)"
    echo "**Commit**: $(git rev-parse --short HEAD 2>/dev/null)"
    echo "**Branch**: $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
    echo ""
    echo "| OP | 基线 QPS | 当前 QPS | Δ% | 判定 |"
    echo "|----|---------|---------|----|------|"
} > "$REPORT_FILE"

for op in DELETE INSERT SELECT UPDATE; do
    if [ -z "${BASELINE[$op]}" ] || [ -z "${CURRENT[$op]}" ]; then
        echo "$op: missing data, skipped"
        continue
    fi

    BASE=${BASELINE[$op]}
    CUR=${CURRENT[$op]}

    # 计算 Δ% (退化率): (BASE - CUR) / BASE * 100
    # 正值 = 性能下降（坏），负值 = 性能提升（好）
    DELTA=$(awk -v b="$BASE" -v c="$CUR" 'BEGIN { printf "%.2f", (b - c) / b * 100 }')

    # 判定
    STATUS="PASS"
    DIR_ICON="→"
    AWK_OK=$(awk -v d="$DELTA" 'BEGIN { print (d < 0) ? 1 : 0 }')
    if [ "$AWK_OK" = "1" ]; then
        DIR_ICON="↑"  # 性能提升
        STATUS="PASS (improved)"
    elif awk -v d="$DELTA" 'BEGIN { exit !(d <= 5) }'; then
        STATUS="PASS"
    elif awk -v d="$DELTA" 'BEGIN { exit !(d <= 20) }'; then
        STATUS="WARN"
    else
        STATUS="FAIL"
    fi

    printf "%-10s %-12s %-12s %-10s %-10s %-8s\n" \
        "$op" "$BASE" "$CUR" "$DELTA%" "$DIR_ICON" "$STATUS"

    # 记录到 markdown 报告
    echo "| $op | $BASE | $CUR | $DELTA% | $STATUS |" >> "$REPORT_FILE"

    # 跟踪最差状态
    if [ "$STATUS" = "FAIL" ] || [ "$STATUS" = "WARN" ]; then
        WORST_STATUS="$STATUS"
        WORST_OP="$op"
        WORST_DELTA=$DELTA
    fi
done

echo ""
echo "=== Summary ==="
echo "Worst status: $WORST_STATUS"
echo "Worst op:     $WORST_OP (Δ = $WORST_DELTA%)"
echo "Report:       $REPORT_FILE"
echo ""

case "$WORST_STATUS" in
    PASS) EXIT_CODE=0; echo "✅ All checks passed" ;;
    WARN) EXIT_CODE=2; echo "⚠️  Warnings detected" ;;
    FAIL) EXIT_CODE=1; echo "❌ Regression detected" ;;
    *)    EXIT_CODE=0 ;;
esac

# 在 markdown 报告加总结
{
    echo ""
    echo "## 总结"
    echo ""
    echo "- **最差判定**: $WORST_STATUS"
    echo "- **最差操作**: $WORST_OP"
    echo "- **退化率**: $WORST_DELTA%"
    echo ""
    echo "## 阈值"
    echo ""
    echo "- PASS:  Δ ≤ ${WARN_THRESHOLD}%"
    echo "- WARN:  ${WARN_THRESHOLD}% < Δ ≤ ${FAIL_THRESHOLD}%"
    echo "- FAIL:  Δ > ${FAIL_THRESHOLD}%"
} >> "$REPORT_FILE"

exit $EXIT_CODE
